version: '1'
services:
  db:
    container_name: postgrestgbot
    image: postgres:13
    volumes:
      - postgrestgbot:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgrestgbot
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sample_db: { }