CREATE TABLE ACTIVE_CHAT
(
    ID       SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID  INTEGER            NOT NULL,
    DATE     INTEGER            NOT NULL,
    DATETIME INTEGER            NOT NULL
);

CREATE TABLE INCOMES
(
    ID       SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID  INTEGER            NOT NULL,
    INCOME   INTEGER,
    DATE     INTEGER            NOT NULL,
    DATETIME INTEGER            NOT NULL
);

CREATE TABLE SPEND
(
    ID       SERIAL PRIMARY KEY NOT NULL,
    CHAT_ID  INTEGER            NOT NULL,
    SPEND    INTEGER,
    DATE     INTEGER            NOT NULL,
    DATETIME INTEGER            NOT NULL
)